### ISSUE TITLE
Some "funny" bugs (not reproducible)

### ISSUE THREAD

**Issue by lluxia** [NotAHero04/inventory-mod#2] opened 2023-12-30 09:07 UTC
Hello,
Some "fun" stuff I noticed running your mod client-side:
- The TPS significantly drops while in the inventory/crafting window compared to playing without the mod (10.8 at the lowest vs. 20... the lag fest is insane)
- In Survival mode, pre-existing stacks of items before the mod was added will either refuse to stack together or the mod will delete the pre-existing stacks entirely; it did work once like a randomized chance.
- ****While gathering materials in Survival mode, items will only stack to 64 and can't be combined to stack past that default value.****
- In Creative mode, if I grab a max stack of an item (i.e., saplings) and then open a chest, all the max stack of items I grabbed from the creative menu disappears from my Hotbar
- If I grab a max stack of items and put it in the Hotbar and the survival inventory, switch to Survival mode and open a chest, both stacks I grabbed from Creative disappear.

**Comment by NotAHero04** [comment] 2023-12-30 10:42
Thanks for your report!
However, I wasn't able to recreate all of the issues you found in the latest beta2 build for 1.20. Try it [here](https://github.com/NotAHero04/inventory-mod/actions/runs/7363669557) to see if any of your issues are resolved.

**Comment by lluxia** [comment] 2023-12-31 04:33
With the beta2 build:
- TPS is significantly improved in inventory/crafting window (consistently 19.3 at the lowest to 20, woo-hoo!)
- In Survival mode, the pre-existing stacks of items before the mod was added will still refuse to stack together, however no more deletions occur
- Newly gathered materials in Survival mode still automatically stack to 64 and cannot be stacked past the default value
- The last two points I mentioned previously about grabbing materials from Creative and opening a chest in either Creative or Survival mode will still automatically delete the items grabbed from the Creative menu. However, further testing reveals: if I grab a stack of 65-70, the stack turns to 64 and stays. If the stack is 71-73, the stack turns to 55 and stays. If the stack is 74-79, the stack turns to 63 and stays. However, the moment the stack is 80 or higher, the stack automatically disappears upon opening a chest.
- FUN FACT: If I try to scroll a new stack of 64 with the Item Scroller mod I had active since the beginning into a chest, it looked like the previous 64 stack in the chest and the new stack in my inventory attempted to stack together (it briefly turned to 128 for a second), however it ended up making a new stack in the chest instead.

**Comment by NotAHero04** [comment] 2023-12-31 07:17
The issue with items taken from creative inventory should be fixed [with this mixin](https://github.com/NotAHero04/inventory-mod/blob/1.20/src/main/java/com/negativeonehero/inventorymod/mixin/ServerPlayNetworkHandlerMixin.java), in fact this is [copied](https://github.com/Devan-Kerman/Stacc/blob/5b28072d18781be3ac627b1ca8f55fd7a91834b9/src/main/java/net/devtech/stacc/mixin/CreativeDesyncFixin.java) from Stacc.
I think there is a conflict with some other mods. Please attach your launcher log here.

**Comment by lluxia** [comment] 2023-12-31 08:24
Considering my track record with downloading mods that catch my fancy for kicks and giggles, I won't be surprised if it is a mod conflict. The log can be found [here](https://mclo.gs/DLWa3DJ).

**Comment by NotAHero04** [comment] 2023-12-31 16:12
This is getting weird. Here's my try with Item Scroller mod:

https://github.com/NotAHero04/inventory-mod/assets/84689840/bc3138d8-0876-4f8c-aa13-0a92d19c80ca

It does seem to work fine... While there's some issues about the holding stack getting de-synchronized when transferring to the chest, that's about it.
I will update to you if something wrong happens.

**Comment by NotAHero04** [comment] 2024-01-01 01:55
Happy New Year, it's me again.

I just tried your set of mods, though on MC 1.20.1, and I can confirm that these things work on my side.
- Newly gathered items still stack normally above 64. I can even merge like stacks and nothing breaks.
- Grabbing items from Creative and then putting it in a container (I tested with a barrel) works fine.
- Item Scroller mod also works (like above).

However, I was able to fix one bug while testing, which is the log spam. It was caused by my mod trying to parse empty strings from EMI.

**Comment by lluxia** [comment] 2024-01-01 04:19
If I remember the release notes correctly, starting Minecraft Java 1.20.2 was incompatible with worlds generated using 1.20.1 and below hence 1.20.2 and 1.20.3/4 mods had to be rebuilt due to the internal changes made in the coding of the base game. There were a lot of code changes and a lot more commands added. So it could be from the fact I'm running 1.20.4.

**Comment by NotAHero04** [comment] 2024-01-02 15:55
After many desperate attempts (and some sleepless hours) to recreate all of your issues, I still fail badly (as always).
This issues will temporarily be closed; however it's already pinned, so I can get back to it when I find something.

**Comment by NotAHero04** [comment] 2024-01-06 16:52
Hi,
I have addressed some of my oversights in [this build](https://github.com/NotAHero04/inventory-mod/actions/runs/7432785211). Please check if any of your issues has been resolved. Thanks.

**Closed as not planned** 2024-01-11 04:11 UTC
Labels: help wanted
